name: grocery
description: A new Flutter project.


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.23.0+1
  flutter_staggered_grid_view: ^0.4.1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.9
  http: ^0.12.0+2
  flutter_auth: ^0.0.1
  fluttertoast: ^8.0.8
  webview_flutter: ^2.3.1
  shared_preferences: any
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/images/beverages_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/
    - assets/images/login_bg.png
    - assets/skills/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/AvenirLight.ttf
        - asset: assets/fonts/gilroy/FuturaLight.ttf
        - asset: assets/fonts/gilroy/luloclean.ttf